name: synthetic_shapenet
class_name: nemo.datasets.synthetic_shapenet.SyntheticShapeNet
root_path: data/DST-pose-fix-distance
shapenet_path: data/ShapeNet/Reconstruct

synset_name:
    car: "02958343"
    chair: "03001627"
    motorbike: "03790512"

render_scale:
    car: 0.9
    chair: 0.7
    motorbike: 0.9

num_models:
    train: 2000
    val: 500

sampler:
    class_name: nemo.torch_utils.misc.InfiniteSampler
