name: synthetic_shapenet
class_name: nemo.datasets.synthetic_shapenet.SyntheticShapeNet
root_path: data/CorrData

synset_name:
    car: "02958343"
    chair: "03001627"
    motorbike: "03790512"

image_sizes: 512
num_verts: 3072

render_scale:
    car: 0.9
    chair: 0.7
    motorbike: 0.9

num_models:
    train: 30
    val: 10

sampler: None
